version: 0.2
phases:
  install:
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - pytest --maxfail=1 --disable-warnings -q
  build:
    commands:
      - docker build -t devops-demo .
artifacts:
  files:
    - '**/*'
