version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"

  redis:
    image: redis:7
    restart: always
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local

